---
# In this case the image is already staged so this should be a success despite the failed statement above
- getval: .+Super package already added
  result:
    present: true
- getval: .+Same Image File-No Change
  result:
    present: true

#These are not definitive, for instance if the above shows existing and present then a "fail" isnt actually a fail
- getval: '^SUCCESS: install_add'
  result:
    success: true
    present: true
- getval: '^FAILED: install_add'
  result:
    success: false