# In this case the image is already staged so this should be a success despite the failed statement above
- getval: 'Super package already added'
  result:
    success: true
    present: true

- getval: '^FAILED: install_add'
  result:
    success: false

- getval: '^SUCCESS: install_add'
  result:
    success: true
    present: true
    installed: true