---
# In this case the image is already staged so this should be a success despite the failed statement above
- getval: .+Super package already added
  result:
    present: true
- getval: .+Same Image File-No Change
  result:
    present: true

#These are not definitive, for instance if the above shows existing and present then a "fail" isnt actually a fail
- example: "Image added. Version: 17.12.05a.0.159"
  getval: '^Image added\. Version: (?P<version>\d+\.\d+\.\d+\w)'
  result:
    newinstall: true
    version: "{{ version }}"
- getval: '^SUCCESS: install_add'
  result:
    success: true
- getval: '^FAILED: install_add'
  result:
    success: false