version: 3

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:2.18.5-1
    # Alternate option for Ansible Automation Platform support
    #name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:1.0
options:
  package_manager_path: '/usr/bin/microdnf'

additional_build_files:
  - src: Source
    dest: Source

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_runner:
    package_pip: ansible-runner>=2.0.0
  ansible_core:
    package_pip: ansible-core>=2.15.0
  galaxy:
    collections:
      - source: Source
        type: dir
  exclude:
    system:
    # We use Python 3.11 so don't install these for cisco.ios deps
    - ~python3-.+

